"""Email service — sends transactional emails via SMTP with language support.

v0.61b — template polish:
  - Full HTML5 doc with <head> for color-scheme meta, preheader, dark-mode
    media queries. Replaces the bare <div> wrapper used through v0.60.
  - Table-based layout for Outlook / mobile-client reliability.
  - @media (prefers-color-scheme: dark) overrides for Apple Mail, iOS Mail,
    Windows Mail, and Outlook.com where the user has dark mode on. Gmail's
    "differential dark mode" is not fully addressable from CSS — we rely on
    its default colour-inversion, which our palette tolerates.
  - Preheader text so inbox list shows "Confirm your spot" / similar instead
    of "Hi {name},".
  - Plain-text alternative attached alongside HTML for deliverability +
    accessibility + text-only clients.
  - Bulletproof CTA buttons ≥44px tall (iOS tap-target minimum).
  - English copy refined. DE/KO/ES/pt-BR/FR strings left untouched — they
    will be regenerated by the external translation pipeline in v0.70 and
    dropped back in wholesale.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from html import escape as _html_escape

from app.core.config import get_settings
from app.core.logging import get_logger

logger = get_logger(__name__)

# ─── Brand palette ───
# Keep in sync with frontend/src/index.css design tokens. Light values are the
# baseline (inline style); dark values are applied via media query classes.
_LIGHT_APP_BG = "#F7F5F2"
_LIGHT_CARD_BG = "#FFFFFF"
_LIGHT_TEXT_PRIMARY = "#0F1E2E"
_LIGHT_TEXT_MUTED = "#4B5A6B"
_LIGHT_TEXT_SUBTLE = "#8893A0"
_LIGHT_ACCENT = "#4682B4"  # Steel Blue
_LIGHT_CODE_BG = "#EAF2F9"

_DARK_APP_BG = "#0F1E2E"
_DARK_CARD_BG = "#1A2C40"
_DARK_TEXT_PRIMARY = "#F7F5F2"
_DARK_TEXT_MUTED = "#B4C0CC"
_DARK_ACCENT = "#FFD700"  # Gold
_DARK_CODE_BG = "#233A52"

_FONT_STACK = "'Nunito Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, Helvetica, sans-serif"

# ─── Translations for transactional emails ───
# v0.61b: English strings refined; other languages intentionally unchanged
# (the external translation pipeline will regenerate them in v0.70).
EMAIL_STRINGS = {
    'en': {
        'confirm_subject':          'Confirm your registration for {event}',
        'confirm_preheader':        'One quick click to save your spot.',
        'confirm_hi':               'Hi {name},',
        'confirm_body':             "Thanks for signing up for <strong>{event}</strong>. We just need you to confirm your registration so we can save your spot.",
        'confirm_button':           'Confirm registration',
        'confirm_fallback_pre':     "If the button above doesn't work, copy and paste this link into your browser:",
        'confirm_footer':           "If you didn't register for this event, you can safely ignore this email.",
        'receipt_subject':          "You're registered for {event}",
        'receipt_preheader':        'Your registration is confirmed. Here are the details.',
        'receipt_hi':               'Hi {name},',
        'receipt_body':             "You're all set for <strong>{event}</strong>. Your registration is confirmed.",
        'receipt_group_code_title': 'Your group code',
        'receipt_group_code_hint':  "Share this code with the people you'd like to be grouped with. When they register, they can enter this code to link up with you. You may also need it at check-in.",
        'receipt_closing':          "We'll be in touch with everything you need to know before the event.",
        'powered_by':               'Powered by Moimio',
    },
    # ── untouched — regenerated in v0.70 ───────────────────────────────
    'de': {
        'confirm_subject': 'Bitte bestätige deine Anmeldung — {event}',
        'confirm_preheader': 'Bitte bestätige deine Anmeldung.',
        'confirm_hi': 'Hallo {name},',
        'confirm_body': 'Vielen Dank für deine Anmeldung für <strong>{event}</strong>. Bitte bestätige deine Anmeldung über den folgenden Button:',
        'confirm_button': 'Anmeldung bestätigen',
        'confirm_fallback_pre': 'Falls der Button nicht funktioniert, kopiere diesen Link in deinen Browser:',
        'confirm_footer': 'Wenn du dich nicht für dieses Event angemeldet hast, kannst du diese E-Mail ignorieren.',
        'receipt_subject': 'Anmeldung bestätigt — {event}',
        'receipt_preheader': 'Deine Anmeldung ist bestätigt.',
        'receipt_hi': 'Hallo {name},',
        'receipt_body': 'Deine Anmeldung für <strong>{event}</strong> wurde bestätigt. ✓',
        'receipt_group_code_title': 'Dein Gruppencode',
        'receipt_group_code_hint': 'Teile diesen Code mit den Mitgliedern deiner Gruppe, wenn sie sich anmelden. Sie können diesen Code den Organisatoren mitteilen, um für Zimmer- und Gruppenzuweisungen verknüpft zu werden.',
        'receipt_closing': 'Das Organisationsteam wird sich in Kürze mit weiteren Informationen melden.',
        'powered_by': 'Powered by Moimio',
    },
    'ko': {
        'confirm_subject': '등록 확인 요청 — {event}',
        'confirm_preheader': '등록을 확인해 주세요.',
        'confirm_hi': '{name}님, 안녕하세요.',
        'confirm_body': '<strong>{event}</strong> 행사에 등록해 주셔서 감사합니다. 아래 버튼을 클릭하여 등록을 확인해 주세요:',
        'confirm_button': '등록 확인',
        'confirm_fallback_pre': '버튼이 작동하지 않는 경우 아래 링크를 브라우저에 복사해 주세요:',
        'confirm_footer': '이 행사에 등록하지 않으셨다면 이 이메일을 무시하셔도 됩니다.',
        'receipt_subject': '등록 완료 — {event}',
        'receipt_preheader': '등록이 완료되었습니다.',
        'receipt_hi': '{name}님, 안녕하세요.',
        'receipt_body': '<strong>{event}</strong> 행사 등록이 완료되었습니다. ✓',
        'receipt_group_code_title': '그룹 코드',
        'receipt_group_code_hint': '그룹원이 등록할 때 이 코드를 공유해 주세요. 주최자에게 이 코드를 알려주시면 방 및 그룹 배정 시 함께 묶입니다.',
        'receipt_closing': '주최팀에서 추가 정보를 곧 보내드릴 것입니다.',
        'powered_by': 'Moimio 제공',
    },
    'es': {
        'confirm_subject': 'Confirma tu inscripción — {event}',
        'confirm_preheader': 'Confirma tu inscripción.',
        'confirm_hi': 'Hola {name},',
        'confirm_body': 'Gracias por inscribirte en <strong>{event}</strong>. Por favor confirma tu inscripción haciendo clic en el botón de abajo:',
        'confirm_button': 'Confirmar inscripción',
        'confirm_fallback_pre': 'Si el botón no funciona, copia y pega este enlace en tu navegador:',
        'confirm_footer': 'Si no te inscribiste en este evento, puedes ignorar este correo.',
        'receipt_subject': 'Inscripción confirmada — {event}',
        'receipt_preheader': 'Tu inscripción está confirmada.',
        'receipt_hi': 'Hola {name},',
        'receipt_body': 'Tu inscripción en <strong>{event}</strong> ha sido confirmada. ✓',
        'receipt_group_code_title': 'Tu código de grupo',
        'receipt_group_code_hint': 'Comparte este código con los miembros de tu grupo cuando se inscriban para que se les agrupe contigo.',
        'receipt_closing': 'El equipo organizador te enviará más información pronto.',
        'powered_by': 'Desarrollado por Moimio',
    },
    'pt-BR': {
        'confirm_subject': 'Confirme sua inscrição — {event}',
        'confirm_preheader': 'Confirme sua inscrição.',
        'confirm_hi': 'Olá {name},',
        'confirm_body': 'Obrigado por se inscrever em <strong>{event}</strong>. Por favor, confirme sua inscrição clicando no botão abaixo:',
        'confirm_button': 'Confirmar inscrição',
        'confirm_fallback_pre': 'Se o botão não funcionar, copie e cole este link no seu navegador:',
        'confirm_footer': 'Se você não se inscreveu neste evento, pode ignorar este e-mail.',
        'receipt_subject': 'Inscrição confirmada — {event}',
        'receipt_preheader': 'Sua inscrição está confirmada.',
        'receipt_hi': 'Olá {name},',
        'receipt_body': 'Sua inscrição em <strong>{event}</strong> foi confirmada. ✓',
        'receipt_group_code_title': 'Seu código de grupo',
        'receipt_group_code_hint': 'Compartilhe este código com os membros do seu grupo ao se inscreverem para que sejam agrupados com você.',
        'receipt_closing': 'A equipe organizadora enviará mais informações em breve.',
        'powered_by': 'Desenvolvido por Moimio',
    },
    'fr': {
        'confirm_subject': 'Confirmez votre inscription — {event}',
        'confirm_preheader': 'Confirmez votre inscription.',
        'confirm_hi': 'Bonjour {name},',
        'confirm_body': "Merci de vous être inscrit(e) à <strong>{event}</strong>. Veuillez confirmer votre inscription en cliquant sur le bouton ci-dessous :",
        'confirm_button': "Confirmer l'inscription",
        'confirm_fallback_pre': 'Si le bouton ne fonctionne pas, copiez ce lien dans votre navigateur :',
        'confirm_footer': "Si vous ne vous êtes pas inscrit(e) à cet événement, vous pouvez ignorer cet e-mail.",
        'receipt_subject': 'Inscription confirmée — {event}',
        'receipt_preheader': 'Votre inscription est confirmée.',
        'receipt_hi': 'Bonjour {name},',
        'receipt_body': 'Votre inscription à <strong>{event}</strong> a été confirmée. ✓',
        'receipt_group_code_title': 'Votre code de groupe',
        'receipt_group_code_hint': 'Partagez ce code avec les membres de votre groupe lors de leur inscription pour être regroupés ensemble.',
        'receipt_closing': "L'équipe organisatrice vous enverra de plus amples informations bientôt.",
        'powered_by': 'Propulsé par Moimio',
    },
}


def _s(lang: str, key: str) -> str:
    """Get a translated string, falling back to English."""
    return EMAIL_STRINGS.get(lang, EMAIL_STRINGS['en']).get(key, EMAIL_STRINGS['en'][key])


# ─── HTML building blocks ─────────────────────────────────────────────────

def _shell(*, title: str, preheader: str, body_html: str, lang: str = 'en') -> str:
    """Wrap content in a full HTML5 document with dark-mode support."""
    # Hidden preheader — harvested as inbox preview but invisible on open.
    # Trailing padding chars prevent leakage from body content.
    hidden_preheader = (
        f'<div style="display:none; font-size:1px; color:{_LIGHT_APP_BG}; '
        f'line-height:1px; max-height:0px; max-width:0px; opacity:0; overflow:hidden; '
        f'mso-hide:all;">{_html_escape(preheader)}'
        f'&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;&#8199;&#65279;</div>'
    )

    return f"""<!doctype html>
<html lang="{_html_escape(lang)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<meta name="supported-color-schemes" content="light dark">
<title>{_html_escape(title)}</title>
<style>
  body {{ margin: 0 !important; padding: 0 !important; width: 100% !important; -webkit-font-smoothing: antialiased; }}
  table {{ border-collapse: collapse; }}
  img {{ border: 0; display: block; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }}
  a {{ text-decoration: none; }}

  @media only screen and (max-width: 480px) {{
    .m-px-16 {{ padding-left: 16px !important; padding-right: 16px !important; }}
    .m-py-24 {{ padding-top: 24px !important; padding-bottom: 24px !important; }}
    .m-button {{ display: block !important; width: 100% !important; box-sizing: border-box !important; }}
  }}

  @media (prefers-color-scheme: dark) {{
    .app-bg      {{ background-color: {_DARK_APP_BG} !important; }}
    .card-bg     {{ background-color: {_DARK_CARD_BG} !important; }}
    .text-primary {{ color: {_DARK_TEXT_PRIMARY} !important; }}
    .text-muted  {{ color: {_DARK_TEXT_MUTED} !important; }}
    .text-subtle {{ color: {_DARK_TEXT_MUTED} !important; }}
    .cta-btn     {{ background-color: {_DARK_ACCENT} !important; color: {_DARK_APP_BG} !important; }}
    .cta-btn a   {{ color: {_DARK_APP_BG} !important; }}
    .code-bg     {{ background-color: {_DARK_CODE_BG} !important; }}
    .code-value  {{ color: {_DARK_ACCENT} !important; }}
    .logo-accent {{ color: {_DARK_ACCENT} !important; }}
    .hairline    {{ border-color: rgba(255,255,255,0.08) !important; }}
  }}

  [data-ogsc] .app-bg      {{ background-color: {_DARK_APP_BG} !important; }}
  [data-ogsc] .card-bg     {{ background-color: {_DARK_CARD_BG} !important; }}
  [data-ogsc] .text-primary {{ color: {_DARK_TEXT_PRIMARY} !important; }}
  [data-ogsc] .text-muted  {{ color: {_DARK_TEXT_MUTED} !important; }}
  [data-ogsc] .text-subtle {{ color: {_DARK_TEXT_MUTED} !important; }}
  [data-ogsc] .cta-btn     {{ background-color: {_DARK_ACCENT} !important; color: {_DARK_APP_BG} !important; }}
  [data-ogsc] .cta-btn a   {{ color: {_DARK_APP_BG} !important; }}
  [data-ogsc] .code-bg     {{ background-color: {_DARK_CODE_BG} !important; }}
  [data-ogsc] .code-value  {{ color: {_DARK_ACCENT} !important; }}
  [data-ogsc] .logo-accent {{ color: {_DARK_ACCENT} !important; }}
</style>
</head>
<body class="app-bg" style="background-color: {_LIGHT_APP_BG}; margin: 0; padding: 0;">
{hidden_preheader}
<table role="presentation" class="app-bg" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color: {_LIGHT_APP_BG};">
  <tr>
    <td align="center" style="padding: 32px 16px;">
      <table role="presentation" class="card-bg" cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width: 540px; background-color: {_LIGHT_CARD_BG}; border-radius: 12px;">
        <tr>
          <td class="m-px-16 m-py-24" style="padding: 32px; font-family: {_FONT_STACK}; font-size: 15px; line-height: 1.55; color: {_LIGHT_TEXT_PRIMARY};">
            {body_html}
          </td>
        </tr>
      </table>
      <p class="text-subtle" style="margin: 16px 0 0 0; font-family: {_FONT_STACK}; font-size: 11px; color: {_LIGHT_TEXT_SUBTLE};">
        {_html_escape(_s(lang, 'powered_by'))}
      </p>
    </td>
  </tr>
</table>
</body>
</html>"""


def _logo() -> str:
    """Brand wordmark — two-tone split."""
    return (
        f'<div style="margin: 0 0 20px 0; font-family: {_FONT_STACK}; '
        f'font-weight: 800; font-size: 22px; letter-spacing: 0.01em;">'
        f'<span class="text-primary" style="color: {_LIGHT_TEXT_PRIMARY};">MOIM</span>'
        f'<span class="logo-accent" style="color: {_LIGHT_ACCENT}; font-size: 0.7em; vertical-align: baseline;">io</span>'
        f'</div>'
    )


def _button(url: str, label: str) -> str:
    """Bulletproof CTA button — ≥44px tall, full-width on mobile."""
    safe_url = _html_escape(url, quote=True)
    safe_label = _html_escape(label)
    return f"""
<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin: 24px 0;">
  <tr>
    <td align="center" bgcolor="{_LIGHT_ACCENT}" class="cta-btn" style="background-color: {_LIGHT_ACCENT}; border-radius: 8px;">
      <a href="{safe_url}" class="m-button" style="display: inline-block; padding: 14px 28px; font-family: {_FONT_STACK}; font-size: 15px; font-weight: 700; color: #FFFFFF; text-decoration: none; border-radius: 8px; mso-padding-alt: 0; line-height: 1.2;">
        <!--[if mso]>&nbsp;&nbsp;&nbsp;<![endif]-->{safe_label}<!--[if mso]>&nbsp;&nbsp;&nbsp;<![endif]-->
      </a>
    </td>
  </tr>
</table>"""


def _p(text: str, *, muted: bool = False, size: str = "15px", margin_top: str = "0") -> str:
    """Paragraph helper. `text` may contain trusted inline HTML (e.g. <strong>)."""
    color = _LIGHT_TEXT_MUTED if muted else _LIGHT_TEXT_PRIMARY
    klass = "text-muted" if muted else "text-primary"
    return (
        f'<p class="{klass}" style="margin: {margin_top} 0 12px 0; '
        f'font-family: {_FONT_STACK}; font-size: {size}; line-height: 1.55; '
        f'color: {color};">{text}</p>'
    )


def _hairline() -> str:
    return (
        f'<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" '
        f'class="hairline" style="border-top: 1px solid rgba(15,30,46,0.08); margin: 20px 0;">'
        f'<tr><td style="height:0; line-height:0;">&nbsp;</td></tr></table>'
    )


def _html_to_text(html_like: str) -> str:
    """Minimal HTML→text for the plain-text alternative."""
    s = html_like
    for tag in ('<strong>', '</strong>', '<em>', '</em>', '<b>', '</b>', '<i>', '</i>'):
        s = s.replace(tag, '')
    return s


# ─── SMTP transport ───────────────────────────────────────────────────────

def send_email(to_email: str, subject: str, html_body: str, text_body: str | None = None) -> bool:
    """Send an email. Returns True on success, False otherwise.

    v0.61b: accepts optional plain-text alternative. When provided, it's
    attached first so it becomes the fallback for text-only clients; the
    HTML part is attached second so it's preferred by HTML-capable clients
    (RFC 2046 §5.1.4 — last alternative wins).
    """
    settings = get_settings()

    if not settings.smtp_enabled:
        logger.warning("email_skipped", reason="SMTP not configured", to=to_email)
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"{settings.smtp_from_name} <{settings.smtp_from_email}>"
        msg["To"] = to_email
        if text_body:
            msg.attach(MIMEText(text_body, "plain", "utf-8"))
        msg.attach(MIMEText(html_body, "html", "utf-8"))

        if settings.smtp_ssl:
            server = smtplib.SMTP_SSL(settings.smtp_host, settings.smtp_port)
        elif settings.smtp_tls:
            server = smtplib.SMTP(settings.smtp_host, settings.smtp_port)
            server.starttls()
        else:
            server = smtplib.SMTP(settings.smtp_host, settings.smtp_port)

        server.login(settings.smtp_user, settings.smtp_password)
        server.sendmail(settings.smtp_from_email, to_email, msg.as_string())
        server.quit()

        logger.info("email_sent", to=to_email, subject=subject)
        return True

    except Exception as e:
        logger.error("email_failed", to=to_email, error=str(e))
        return False


# ─── Transactional emails ─────────────────────────────────────────────────

def send_confirmation_email(
    to_email: str, first_name: str, event_name: str, confirmation_url: str, lang: str = 'en'
) -> bool:
    """Ask a participant to confirm their pending registration."""
    L = lang if lang in EMAIL_STRINGS else 'en'
    subject = _s(L, 'confirm_subject').format(event=event_name)

    safe_name = _html_escape(first_name)
    safe_event = _html_escape(event_name)
    safe_url = _html_escape(confirmation_url, quote=True)

    body_html = (
        _logo()
        + _p(_s(L, 'confirm_hi').format(name=safe_name))
        + _p(_s(L, 'confirm_body').format(event=safe_event))
        + _button(confirmation_url, _s(L, 'confirm_button'))
        + _p(_s(L, 'confirm_fallback_pre'), muted=True, size="13px", margin_top="8px")
        + f'<p class="text-muted" style="margin: 0 0 20px 0; font-family: {_FONT_STACK}; '
          f'font-size: 12px; line-height: 1.5; word-break: break-all; color: {_LIGHT_TEXT_MUTED};">'
          f'<a href="{safe_url}" class="logo-accent" '
          f'style="color: {_LIGHT_ACCENT}; text-decoration: underline;">'
          f'{_html_escape(confirmation_url)}</a></p>'
        + _hairline()
        + _p(_s(L, 'confirm_footer'), muted=True, size="12px")
    )

    html = _shell(
        title=subject,
        preheader=_s(L, 'confirm_preheader'),
        body_html=body_html,
        lang=L,
    )

    text = (
        f"{_html_to_text(_s(L, 'confirm_hi').format(name=first_name))}\n\n"
        f"{_html_to_text(_s(L, 'confirm_body').format(event=event_name))}\n\n"
        f"{_s(L, 'confirm_button')}:\n{confirmation_url}\n\n"
        f"{_s(L, 'confirm_footer')}\n\n"
        f"— {_s(L, 'powered_by')}\n"
    )

    return send_email(to_email, subject, html, text)


def send_registration_confirmed(
    to_email: str, first_name: str, event_name: str, group_code: str | None = None, lang: str = 'en'
) -> bool:
    """Send a post-confirmation receipt. Includes the group code when present."""
    L = lang if lang in EMAIL_STRINGS else 'en'
    subject = _s(L, 'receipt_subject').format(event=event_name)

    safe_name = _html_escape(first_name)
    safe_event = _html_escape(event_name)

    group_code_section = ""
    if group_code:
        safe_code = _html_escape(group_code)
        group_code_section = f"""
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"
       class="code-bg" style="background-color: {_LIGHT_CODE_BG}; border-radius: 10px; margin: 4px 0 16px 0;">
  <tr>
    <td style="padding: 16px 20px;">
      <p class="text-subtle" style="margin: 0 0 6px 0; font-family: {_FONT_STACK}; font-size: 11px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; color: {_LIGHT_TEXT_SUBTLE};">
        {_html_escape(_s(L, 'receipt_group_code_title'))}
      </p>
      <p class="code-value" style="margin: 0 0 10px 0; font-family: 'Courier New', Consolas, monospace; font-size: 22px; font-weight: 700; letter-spacing: 3px; color: {_LIGHT_ACCENT};">
        {safe_code}
      </p>
      <p class="text-muted" style="margin: 0; font-family: {_FONT_STACK}; font-size: 12px; line-height: 1.5; color: {_LIGHT_TEXT_MUTED};">
        {_html_escape(_s(L, 'receipt_group_code_hint'))}
      </p>
    </td>
  </tr>
</table>"""

    body_html = (
        _logo()
        + _p(_s(L, 'receipt_hi').format(name=safe_name))
        + _p(_s(L, 'receipt_body').format(event=safe_event))
        + group_code_section
        + _p(_s(L, 'receipt_closing'), muted=True)
    )

    html = _shell(
        title=subject,
        preheader=_s(L, 'receipt_preheader'),
        body_html=body_html,
        lang=L,
    )

    text_parts = [
        _html_to_text(_s(L, 'receipt_hi').format(name=first_name)),
        "",
        _html_to_text(_s(L, 'receipt_body').format(event=event_name)),
        "",
    ]
    if group_code:
        text_parts.extend([
            f"{_s(L, 'receipt_group_code_title')}: {group_code}",
            _s(L, 'receipt_group_code_hint'),
            "",
        ])
    text_parts.extend([
        _s(L, 'receipt_closing'),
        "",
        f"— {_s(L, 'powered_by')}",
        "",
    ])
    text = "\n".join(text_parts)

    return send_email(to_email, subject, html, text)


# Backwards-compat alias — callsites in app/api/participants.py use this name.
def send_registration_receipt(
    to_email: str, first_name: str, event_name: str, group_code: str | None = None, lang: str = 'en'
) -> bool:
    return send_registration_confirmed(to_email, first_name, event_name, group_code, lang)


def send_password_reset_email(to_email: str, full_name: str, reset_url: str) -> bool:
    """Password-reset email. English only — admin/staff-facing. v0.70's
    translation overhaul may broaden this."""
    subject = "Reset your Moimio password"
    raw_first = full_name.split()[0] if full_name else "there"
    safe_first = _html_escape(raw_first)
    safe_url = _html_escape(reset_url, quote=True)

    body_html = (
        _logo()
        + _p(f"Hi {safe_first},")
        + _p("We received a request to reset your Moimio password. Click below to choose a new one.")
        + _button(reset_url, "Reset password")
        + _p("This link expires in 30 minutes.", muted=True, size="13px")
        + _p("If you didn't request a password reset, you can safely ignore this email — your password won't change.", muted=True, size="13px")
        + _hairline()
        + _p("If the button above doesn't work, copy and paste this link into your browser:", muted=True, size="12px")
        + f'<p style="margin: 0 0 4px 0; font-family: {_FONT_STACK}; '
          f'font-size: 12px; line-height: 1.5; word-break: break-all;">'
          f'<a href="{safe_url}" class="logo-accent" style="color: {_LIGHT_ACCENT}; '
          f'text-decoration: underline;">{_html_escape(reset_url)}</a></p>'
    )

    html = _shell(
        title=subject,
        preheader="Reset your Moimio password — link expires in 30 minutes.",
        body_html=body_html,
        lang='en',
    )

    text = (
        f"Hi {raw_first},\n\n"
        f"We received a request to reset your Moimio password.\n"
        f"Visit this link to choose a new one:\n\n"
        f"{reset_url}\n\n"
        f"This link expires in 30 minutes.\n"
        f"If you didn't request a password reset, you can ignore this email — your password won't change.\n\n"
        f"— Powered by Moimio\n"
    )

    return send_email(to_email, subject, html, text)


def render_smtp_test_email(
    event_name: str, from_name: str, reply_to: str, smtp_host: str, smtp_port: int
) -> tuple[str, str, str]:
    """Render the SMTP self-test email. Returns (subject, html, text).

    v0.61b: extracted from app/api/events.py so the test email uses the
    same shell as every other email we send. Called from the test-email
    endpoint."""
    subject = f"Moimio SMTP test — {event_name}"

    safe_event = _html_escape(event_name)
    safe_from = _html_escape(from_name)
    safe_reply = _html_escape(reply_to) if reply_to else '<span style="opacity:0.6;">(not set)</span>'
    safe_host = _html_escape(f"{smtp_host}:{smtp_port}")

    body_html = (
        _logo()
        + _p("<strong>SMTP test</strong>")
        + _p(f"This is a test email from <strong>{safe_event}</strong>. "
             f"If you're reading this, your email configuration is working.")
        + _hairline()
        + f'<table role="presentation" cellpadding="0" cellspacing="0" border="0" '
          f'style="margin: 0 0 8px 0; font-family: {_FONT_STACK}; font-size: 12px; line-height: 1.6;">'
          f'<tr><td class="text-subtle" style="color: {_LIGHT_TEXT_SUBTLE}; padding-right: 12px; vertical-align: top;">Sent from</td>'
          f'<td class="text-muted" style="color: {_LIGHT_TEXT_MUTED};">{safe_from}</td></tr>'
          f'<tr><td class="text-subtle" style="color: {_LIGHT_TEXT_SUBTLE}; padding-right: 12px; vertical-align: top;">Reply-to</td>'
          f'<td class="text-muted" style="color: {_LIGHT_TEXT_MUTED};">{safe_reply}</td></tr>'
          f'<tr><td class="text-subtle" style="color: {_LIGHT_TEXT_SUBTLE}; padding-right: 12px; vertical-align: top;">SMTP server</td>'
          f'<td class="text-muted" style="color: {_LIGHT_TEXT_MUTED};">{safe_host}</td></tr>'
          f'</table>'
    )

    html = _shell(
        title=subject,
        preheader="SMTP configuration test — your email is working.",
        body_html=body_html,
        lang='en',
    )

    text = (
        f"SMTP test\n\n"
        f"This is a test email from {event_name}.\n"
        f"If you're reading this, your email configuration is working.\n\n"
        f"Sent from:   {from_name}\n"
        f"Reply-to:    {reply_to or '(not set)'}\n"
        f"SMTP server: {smtp_host}:{smtp_port}\n\n"
        f"— Powered by Moimio\n"
    )

    return subject, html, text
